config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :templates do
    resources :examples, only: [:new,:create]
    resources :outputs, only: [:new, :create]
  end

  resources :outputs, only: [:edit, :update, :show]
  resources :examples, only: [:edit, :update]

  resources :input_fields, only: [:update, :edit]

  root to: "pages#home"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/templates/_form.html.erb
<%= simple_form_for @template, data: { controller: 'submit-loader', action: 'submit->submit-loader#submit' } do |f| %>
    <div class="form-inputs mt-3 title">
      <%= f.input :title, input_html: { class: 'form-control presentation-form-control fs-1  bg-light rounded-3' }, placeholder: "Add Template Title", label: false %>

      <%= f.input :description, input_html: { class: 'form-control bg-light rounded-3' }, placeholder: "Add Description", label: false %>

      <%= f.simple_fields_for :example, @template.example do |exf| %>
      <%= exf.input :id, as: :hidden %>

      <% if !@template.persisted? %>
        <%= exf.input :content, input_html: { class: 'form-control bg-light pb-5 rounded-3' }, placeholder:"Add an example the text", label: false %>
      <% end %>
    <% end %>
    </div>

    <div class="d-flex gap-3 align-items-center mt-5">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', templates_path, class: 'btn my-btn-light' %>
    </div>
  <%= render "shared/loading_hexes" %>
<% end %>

app/views/templates/edit.html.erb
  <div class="container my-5">

<h1 class="display-1 title">Edit template</h1>

<%= render "form", template: @template %>

</div>

app/views/templates/index.html.erb
<div class="container mt-5">
  <h1 class="display-1 title">Templates</h1>

  <div id="template">
    <% @templates.each do |template| %>

      <div class="card flex-md-row mb-3 h-md-250 text-white bg-primary col-12 d-flex justify-content-between p-2 custom-shadow card-presentation ">
        <div class="card-body d-flex flex-column align-items-start">
          <h5 class="card-title"><%= template.title %></h5>
          <p class="card-text"><%= template.description %></p>
        </div>
        <div class="card-body d-flex align-items-end justify-content-end align-items-center">
          <%= link_to edit_example_path(template.example) do %>
            <div class="btn my-btn-light">
              <i class="fa-regular fa-eye"></i>
            </div>
          <% end %>

          <%= link_to template_path(template), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } do %>
          <div class="btn my-btn-light">
              <i class="fa-regular fa-trash-can"></i>
            </div>
          <% end %>

          <%= link_to "Create text", new_template_output_path(template), :class => "btn my-btn-light"  %>
        </div>
      </div></>
    <% end %>
  </div>
</div>

app/views/templates/new.html.erb
<div class="container mt-5">
  <h1 class="display-1">New template</h1>
  
  <%= render "form", template: @template %>

</div>

app/views/templates/show.html.erb
<div class="container my-5">
  <h1 class="display-1"><%= @template.title  %></h1>
  <h2 class="display-2"><%= @template.description %></h2>
</div>
<% if @template.outputs != 0 %>
<div class="container my-5 ">
  <h2 class="display-2 my-3 title">History</h2>

  <div class="d-flex flex-row flex-wrap">
    <% @template.outputs.each_with_index do |output, index| %>
      <div class="w-25 px-2 ">
        <%= link_to output, class: "col-4 mb-4 btn btn-primary" do %>
          <h5 >
            <i class="fa-regular fa-file p-1"></i>
            Version_<%= index + 1 %>
          </h5>

          <div class="fw-normal my-2">
            <%= truncate(output.content, length: 30) %>
          </div>

          <div class="fw-light text-black-50 w-100 text-truncate fs-6">
            <small><%= output.input_fields.map(&:key).to_sentence(last_word_connector: ', ') %></small>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<% end %>
<div class="container my-5">
  <h2 class="display-2">Template preview</h2>
  <div class="my-2">
    <div class="card col-12 bg-light p-3 rounded my-3">
      <p><%= @template.example.content if @template.example %></p>
    </div>
  </div>

  <div class="d-flex gap-3">
    <%= link_to "Use template", new_template_output_path(@template), :class => "btn btn-primary" %>
    <%= link_to "Edit template", (edit_example_path(@template.example) if @template.example), :class => "btn my-btn-light " %>

    <%= link_to 'Back', templates_path, class: 'btn my-btn-light' %>
  </div>
</div>