config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :templates do
    resources :examples, only: [:new,:create]
    resources :outputs, only: [:new, :create]
  end

  resources :outputs, only: [:edit, :update, :show]
  resources :examples, only: [:edit, :update]

  resources :input_fields, only: [:update, :edit]

  root to: "pages#home"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/example.rb
require "json"

class Example < ApplicationRecord
  belongs_to :template
  has_many :example_fields, dependent: :destroy

  accepts_nested_attributes_for :example_fields

  validates :content, presence: true, length: { minimum: 80 }

  def content_with_active_fields_only
    sanitized_content = content

    # For each inactive example field we need to replace <key> with the value
    example_fields.notactive.each do |field|
      sanitized_content.gsub!(/<#{field.key}>/, field.value)
    end

    sanitized_content
  end


  def generate_example_field
    client = OpenAI::Client.new

    example_fields.destroy_all # just in case

    self.initial_content = content
    self.initial_prompt = "Given #{initial_content}, create a JSON object with one level only named 'example_field'
    that follows a standardized format. The output should consist of key-value pairs,
    with each key representing an information keyword extracted from the text,
    and the corresponding value providing relevant information associated with that keyword.
    Ensure the JSON object adheres to a consistent and well-defined structure."
    save

    chaptgpt_response = client.chat(parameters: {
      model: "gpt-4",
      messages: [{ role: "user", content: initial_prompt }]
    })
    json_string = chaptgpt_response["choices"][0]["message"]["content"]

    update(chatgpt_keys: json_string)

    ruby_object = JSON.parse(json_string)
    key_values = ruby_object["example_field"]

    key_values.each do |key, value|
      example_fields.create!(key:, value:)
    end

    generate_content_example
  end

  def generate_content_example
    client = OpenAI::Client.new
    self.intermediate_prompt = "given #{content}, in this text replace each value
    for the corresponding key like <key>considering this json object:
    #{example_fields.pluck(:key, :value).to_h.to_json} like <key>, return me a text"

    save

    chaptgpt_response = client.chat(parameters: {
      model: "gpt-4",
      messages: [{ role: "user", content: intermediate_prompt}]
    })
    output_from_api = chaptgpt_response["choices"][0]["message"]["content"]

    update(content: output_from_api)
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController

  def new
    @template = Template.find(params[:template_id])
    @example = Example.new
  end

  def edit
    @example = Example.find(params[:id])
    @template = @example.template
    @example_fields = @example.example_fields
  end

  def create
    @example = Example.new(example_params)
    @example.template = Template.find(params[:template_id])
    @example.save
    redirect_to edit_example_path(@example)
  end

  def update
    @example = Example.find(params[:id])
    @example.update(example_params)
    redirect_to new_template_output_path(@example.template)
  end

  private

  def example_params
    params.require(:example).permit(:content, :template_id, example_fields_attributes: [:active, :id])
  end
end

app/helpers/examples_helper.rb
module ExamplesHelper
  def content_with_fields(example:, controller:, only_active: false)
    default_content = only_active ? example.content_with_active_fields_only : example.content

    parsed_content = default_content.gsub(/<([[[:alnum:]]_\s]+)>/, "<span class=\"field-tag\" data-#{controller}-target=\"field\" data-value=\"\\1\">\\1</span>")

    example.example_fields.each do |field|
      parsed_content.gsub!(/data-value="#{field.key}"/, "data-value=\"#{field.value}\" data-id=\"#{field.id}\"")
    end

    tag.div parsed_content.html_safe
  end
end

app/views/examples/_form.html.erb
<%= simple_form_for [ @template, @example ] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">

      <%= f.text_area :content, class: 'form-control bg-light pb-5', placeholder:"Add an example the text" %>
    </div>

    <%= f.submit class: 'btn btn-primary mt-5' %>
<% end %>

app/views/examples/edit.html.erb
<div class="container my-5 ">
  <h1 class="display-1" style="display:inline"><%= @template.title  %></h1>
  <h2 style="display:inline">
  <%= link_to edit_template_path(@template) do |f| %>
    <small>  <i class="fa-solid fa-pen"></i></small>
  <% end %>
  </h2>

  <h2 class="display-2"><%= @template.description %>
  <%= link_to edit_template_path(@template) do |f| %>
    <small>  <i class="fa-solid fa-pen"></i></small>
  <% end %>
  </h2>
</div>

<% if @template.outputs.length != 0 %>
<div class="container my-5 ">
  <h2 class="display-2 my-3">History</h2>

  <div class="row">
    <% @template.outputs.each_with_index do |output, index| %>
      <div class="col-3 mb-4">
        <%= link_to output, class: "btn btn-primary w-100 py-2" do %>
          <h5 >
            <i class="fa-regular fa-file p-1"></i>
            Version <%= index + 1 %>
          </h5>

          <div class="fw-normal my-2 text-truncate">
            <%= output.content %>
          </div>

          <div class="fw-light text-light-50 w-100 text-truncate fs-8">
            <small>
              <%= output.input_fields.map(&:key).to_sentence(last_word_connector: ', ') %>
            </small>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<% end %>

<div class="container my-5" data-controller="checkbox-edit">
  <h2 class="display-2">Template preview</h2>
  <%= simple_form_for @example do |f| %>
    <div class="my-2">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class="card col-12 bg-light p-3 rounded my-3">
        <h5 data-checkbox-edit-target="content" class="opacity-0">
          <%= content_with_fields example: @example, controller: 'checkbox-edit' %>
        </h5>
      </div>
    </div>
    <div class="my-5">
      <h2 class="display-2 mb-3 ">Input data</h2>

      <%# display all example_fields as checkboxes %>
      <div class="d-flex flex-row gap-2 flex-wrap">
        <%= f.fields_for :example_fields do |field_subform| %>
        <%= field_subform.hidden_field :id %>
          <%= field_subform.input :active, label: field_subform.object.key,
          input_html: {
            class: 'tag-selector',
            data: {
              action: "click->checkbox-edit#toggleField",
              checkbox_edit_target: "check",
              field_id: field_subform.object.id
            }
          },
          wrapper_html: { class: 'tag-item' } %>
        <% end %>
      </div>
    </div>

    <div class="d-flex gap-3">
      <%= f.submit class: 'btn btn-primary', value: "Save & continue" %>
      <%= link_to 'Back', templates_path, class: 'btn my-btn-light' %>
    </div>
  <% end %>
  </div>
</div>


</div>

app/views/examples/new.html.erb
<div class="container mt-5">
<h1 class="display-1 mb-4"><%= @template.title %></h1>
<h2 class="mb-5"><%= @template.description %></h2>

 <%= render "form", example: @example %>
</div>