config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :templates do
    resources :examples, only: [:new,:create]
    resources :outputs, only: [:new, :create]
  end

  resources :outputs, only: [:edit, :update, :show]
  resources :examples, only: [:edit, :update]

  resources :input_fields, only: [:update, :edit]

  root to: "pages#home"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :template
  has_many :input_fields, dependent: :destroy

  accepts_nested_attributes_for :input_fields
  validates_associated :input_fields

  def generate_output_content
    client = OpenAI::Client.new
    input_fields_hash = template.example_fields.pluck(:key, :value).to_h
                                .merge(input_fields.pluck(:key, :value).to_h)
                                .to_json

    prompt = "given #{template.example.content}, and the following JSON object:
    #{input_fields_hash} replace the keys for the values in the provided text and
    get a full text without any signals"

    update(prompt:)

    chaptgpt_response = client.chat(
      parameters: {
        model: 'gpt-4',
        messages: [{ role: "user", content: prompt }]
      }
    )
    result = chaptgpt_response["choices"][0]["message"]["content"]
    update(content: result)
  end
end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController
  before_action :set_template, only: [:new, :create]

  def new
    @output = Output.new(template: @template)
    @example = @template.example

    init_input_fields
  end

  def create
    @output = params[:output].blank? ? Output.new : Output.new(output_params)
    @output.template = @template
    @example = @template.example

    if @output.save
      @output.generate_output_content
      redirect_to @output
    else
      render :new
    end
  end

  def show
    #vemos o output final
    @output = Output.find(params[:id])
  end

  def edit
    # aqui vamos fazer um form para fazer update ao content do output
    # e dar valores aos input fields (já devem ter keys)
    @output = Output.find(params[:id])
    @template = @output.template
    @example = @template.example
  end

  def update
    #gravar as alteraçoes
    @output = Output.find(params[:id])
    @template = @output.template
    @example = @template.example

    if @output.update(output_params)
      @output.generate_output_content
      redirect_to @output
    else
      render :edit
    end
  end

  private

  def init_input_fields
    @example.example_fields.active.each do |field|
      @output.input_fields << InputField.new(key: field.key, example_field: field)
    end
  end

  def output_params
    params.require(:output).permit(:content, :prompt, input_fields_attributes: [:key, :value, :id, :example_field_id])
  end

  def set_template
    @template = Template.find(params[:template_id])
  end

end

app/views/outputs/_form.html.erb
<%= f.simple_fields_for :input_fields, @output.input_fields do |field| %>
  <div class="row">
    <div class="form-inputs col-10">
      <%= field.input :key, as: :hidden %>
      <%= field.input :example_field_id, as: :hidden %>
      <%= field.input :value, input_html: {
        class: 'form-control bg-light rounded-2 custom-shaddow',
        data: {
          action: "input->realtime-fields#changeText",
          id: field.object.example_field_id,
          realtime_fields_target: "input"
        }},
        placeholder: "Add #{field.object.example_field.key.titleize.downcase}",
        label: field.object.example_field.key.titleize.capitalize
      %>    </div>
  </div>
<% end %>

<div class="d-flex gap-3 my-3">
  <%= f.submit output.persisted? ? 'Update Text' : "Create Text" ,class: 'btn btn-primary' %>

  <% if output.persisted? %>
    <%= link_to 'Back', edit_example_path(@example), class: 'btn my-btn-light' %>
  <% else %>
    <%= link_to 'Back', :back, class: 'btn my-btn-light' %>
  <% end %>
</div>

app/views/outputs/edit.html.erb
<div class="container mt-5">
  <h1 class="display-1">Edit text</h1>
  <div class="row" data-controller="realtime-fields">
    <div class="col-6">
      <%= simple_form_for @output, data: { turbo: false } do |f| %>
        <%= render "form", f: f, output: @output %>
      <% end %>
    </div>

    <div class="col-6 card bg-light p-3 rounded">
      <%= content_with_fields example: @example, controller: 'realtime-fields', only_active: true  %>
    </div>
  </div>
</div>

app/views/outputs/new.html.erb
<div class="container my-5">
  <h1 class="display-1">New text</h1>
  <div class="row" data-controller="realtime-fields">
    <div class="col-4">
    <%= simple_form_for [@template, @output], data: { turbo: false, controller: 'submit-loader', action: 'submit->submit-loader#submit' } do |f| %>
      <%= render "form", f: f, output: @output %>
    <%= render "shared/loading_hexes" %>
    <% end %>
    </div>

      <div class="col-8 card bg-light p-3 rounded fs-5 mt-4 h-25">
        <%= content_with_fields example: @example, controller: 'realtime-fields', only_active: true  %>
      </div>
  </div>
</div>

app/views/outputs/show.html.erb
<div data-controller="clipboard" data-clipboard-feedback-text-value="Copied!">
  <div class="container mt-5">
    <div class="d-flex flex-row mb-3 justify-content-between align-items-center">
      <h1 class="display-1">Output</h1>
      <div class="d-flex flex-row gap-3">
        <button class="btn btn-primary" data-clipboard-target="button"
          data-action="click->clipboard#copy">Copy</button>
          <%= mail_to "recipient@email.com", "Email",
            subject: "#{@output.template.title}",
            body: "#{@output.content}",
            class: "btn btn-primary" %>
        </div>
    </div>

    <div class="col-12 card bg-light p-3 rounded min-output relative flex mb-3 fs-4">
        <div data-clipboard-target="input">
          <%= @output.content %>
        </div>
    </div>
      <div class="d-flex gap-3 mt-3">
        <%= link_to 'Edit template', edit_example_path(@output.template.example),
          class: "btn btn-primary" %>
        <%= link_to 'Back', edit_output_path(@output), class: 'btn my-btn-light' %>

      </div>
    </div>
</div>